//
//  DefaultTemplatesSheet.swift
//  Oversight
//
//  Default document templates — ported from TemplatesSheet in
//  oversight-sheets.jsx. Selected templates auto-generate when a
//  project reaches Abatement Completed (desktop parity, per
//  DOCUMENT_GENERATION.md).
//

import SwiftUI
import SwiftData

struct DefaultTemplatesSheet: View {
    @Environment(\.dismiss) private var dismiss
    @Environment(\.modelContext) private var modelContext
    @Query private var inspectors: [Inspector]

    @State private var selected: Set<DocumentTemplate> = []

    var body: some View {
        NavigationStack {
            Form {
                Section {
                    ForEach(DocumentTemplate.allCases) { template in
                        Button {
                            if selected.contains(template) { selected.remove(template) } else { selected.insert(template) }
                        } label: {
                            HStack {
                                Image(systemName: selected.contains(template) ? "checkmark.square.fill" : "square")
                                    .foregroundStyle(selected.contains(template) ? Color.accentColor : .secondary)
                                VStack(alignment: .leading) {
                                    Text(template.rawValue).foregroundStyle(.primary)
                                    Text(template.summary).font(.caption2).foregroundStyle(.secondary)
                                }
                            }
                        }
                    }
                } header: {
                    Text("Generate automatically")
                } footer: {
                    Text("Selected templates are generated by default when a project reaches Abatement Completed.")
                }
            }
            .navigationTitle("Default Templates")
            .inlineNavTitle()
            .toolbar {
                ToolbarItem(placement: .confirmationAction) { Button("Done") { save(); dismiss() } }
            }
        }
        .onAppear {
            if let inspector = inspectors.first { selected = Set(inspector.defaultTemplates) }
        }
    }

    private func save() {
        let inspector = inspectors.first ?? {
            let created = Inspector()
            modelContext.insert(created)
            return created
        }()
        inspector.defaultTemplates = Array(selected)
        try? modelContext.save()
    }
}
